//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "iterations_tasks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub iteration_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub task_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::iterations::Entity",
        from = "Column::IterationId",
        to = "super::iterations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Iterations,
    #[sea_orm(
        belongs_to = "super::tasks::Entity",
        from = "Column::TaskId",
        to = "super::tasks::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tasks,
}

impl Related<super::iterations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Iterations.def()
    }
}

impl Related<super::tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tasks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
